// Entry fees are per-person Indian-visitor rates in rupees; 0 means free entry.
export const activitiesBySlug = {
  manali: [
    {
      name: 'Hadimba Devi Temple',
      type: 'spiritual',
      description:
        'A four-tiered wooden pagoda temple from 1553, set in a grove of tall deodar trees in Dhungri.',
      location: { lat: 32.2483, lng: 77.1806 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Solang Valley',
      type: 'adventure',
      description:
        'Open meadow below the glaciers with a ropeway, paragliding and zorbing in summer and skiing in winter. The fee covers the ropeway ticket.',
      location: { lat: 32.3166, lng: 77.157 },
      durationHours: 4,
      entryFee: 700,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Rohtang Pass',
      type: 'adventure',
      description:
        'The 3,978 m pass on the Pir Panjal range with snow for most of the season. Vehicles need a permit, shared here per person.',
      location: { lat: 32.3716, lng: 77.2466 },
      durationHours: 5,
      entryFee: 550,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Jogini Waterfall Trek',
      type: 'nature',
      description:
        'An easy trail from Vashisht through apple orchards and pine forest to a 45 m waterfall.',
      location: { lat: 32.2752, lng: 77.188 },
      durationHours: 3,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Sissu via Atal Tunnel',
      type: 'nature',
      description:
        'Drive through the 9 km Atal Tunnel into Lahaul for the Sissu waterfall, the lake and wide Chandra valley views.',
      location: { lat: 32.4689, lng: 77.1323 },
      durationHours: 4,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Vashisht Hot Springs',
      type: 'spiritual',
      description:
        'Natural sulphur springs with public baths beside the old stone Vashisht and Rama temples.',
      location: { lat: 32.2639, lng: 77.1886 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Van Vihar National Park',
      type: 'nature',
      description:
        'A quiet deodar park beside the Beas in the middle of town, with walking paths and a small boating pond.',
      location: { lat: 32.2394, lng: 77.1892 },
      durationHours: 1,
      entryFee: 20,
      rating: 4.0,
      bestTime: 'afternoon',
    },
    {
      name: 'Naggar Castle',
      type: 'culture',
      description:
        'A 15th-century stone-and-timber castle of the Kullu rajas, now a heritage hotel with a small museum and valley views.',
      location: { lat: 32.1118, lng: 77.1646 },
      durationHours: 2,
      entryFee: 30,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Old Manali Cafes',
      type: 'food',
      description:
        'The lane above the Manalsu stream is lined with cafes serving wood-fired trout, Israeli plates and Himachali siddu.',
      location: { lat: 32.2548, lng: 77.176 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'evening',
    },
    {
      name: 'Mall Road Manali',
      type: 'shopping',
      description:
        'The pedestrian main street for Kullu shawls, woollens and local fruit wines, busiest after sunset.',
      location: { lat: 32.2433, lng: 77.189 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'evening',
    },
  ],

  goa: [
    {
      name: 'Fort Aguada',
      type: 'culture',
      description:
        'A 1612 Portuguese fort and lighthouse on the headland above Sinquerim, guarding the mouth of the Mandovi.',
      location: { lat: 15.492, lng: 73.7737 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'morning',
    },
    {
      name: 'Basilica of Bom Jesus',
      type: 'spiritual',
      description:
        'The baroque basilica in Old Goa that holds the relics of St Francis Xavier, part of a UNESCO World Heritage Site.',
      location: { lat: 15.5009, lng: 73.9116 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Se Cathedral',
      type: 'culture',
      description:
        'One of the largest churches in Asia, completed in 1619, known for its Golden Bell and Tuscan facade.',
      location: { lat: 15.5039, lng: 73.9121 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Fontainhas Latin Quarter',
      type: 'culture',
      description:
        'Panaji’s old Portuguese neighbourhood of narrow lanes, tiled-roof houses painted ochre and blue, bakeries and galleries.',
      location: { lat: 15.4968, lng: 73.8313 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'afternoon',
    },
    {
      name: 'Baga Beach Water Sports',
      type: 'adventure',
      description:
        'Parasailing, jet-ski and banana-boat rides off the busiest beach in North Goa. The fee is a typical combo package.',
      location: { lat: 15.5553, lng: 73.7517 },
      durationHours: 2,
      entryFee: 1500,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Anjuna Flea Market',
      type: 'shopping',
      description:
        'A beachside market that began in the hippie era, selling clothes, jewellery, spices and handicrafts.',
      location: { lat: 15.5736, lng: 73.74 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.1,
      bestTime: 'afternoon',
    },
    {
      name: 'Chapora Fort',
      type: 'sightseeing',
      description:
        'Laterite ramparts on a hill above Vagator with a sweeping sunset view of the coast and the Chapora river.',
      location: { lat: 15.606, lng: 73.7366 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'evening',
    },
    {
      name: 'Dudhsagar Falls',
      type: 'nature',
      description:
        'A 310 m four-tiered waterfall on the Mandovi inside Bhagwan Mahavir sanctuary, reached by forest jeep from Kulem.',
      location: { lat: 15.3144, lng: 74.3143 },
      durationHours: 5,
      entryFee: 500,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Palolem Beach',
      type: 'nature',
      description:
        'A calm crescent bay in South Goa fringed with coconut palms, good for swimming, kayaking and dolphin boats.',
      location: { lat: 15.01, lng: 74.0232 },
      durationHours: 3,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Sahakari Spice Farm',
      type: 'food',
      description:
        'A guided walk through a working spice plantation near Ponda followed by a Goan buffet lunch served on banana leaves.',
      location: { lat: 15.4082, lng: 74.0238 },
      durationHours: 2.5,
      entryFee: 500,
      rating: 4.3,
      bestTime: 'any',
    },
  ],

  jaipur: [
    {
      name: 'Amber Fort',
      type: 'culture',
      description:
        'The hilltop palace-fort of the Kachhwaha rulers, with the mirrored Sheesh Mahal and courtyards above Maota Lake.',
      location: { lat: 26.9855, lng: 75.8513 },
      durationHours: 3,
      entryFee: 100,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Hawa Mahal',
      type: 'sightseeing',
      description:
        'The five-storey "Palace of Winds" with 953 latticed windows, built so royal women could watch the street unseen.',
      location: { lat: 26.9239, lng: 75.8267 },
      durationHours: 1,
      entryFee: 50,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'City Palace Jaipur',
      type: 'culture',
      description:
        'The royal residence at the heart of the old city, with museums of textiles and arms and the painted Pritam Niwas Chowk.',
      location: { lat: 26.9258, lng: 75.8237 },
      durationHours: 2,
      entryFee: 200,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Jantar Mantar',
      type: 'culture',
      description:
        'An 18th-century observatory of giant masonry instruments, including the world’s largest stone sundial. UNESCO listed.',
      location: { lat: 26.9248, lng: 75.8246 },
      durationHours: 1,
      entryFee: 50,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Jal Mahal',
      type: 'sightseeing',
      description:
        'A palace that appears to float in Man Sagar Lake, viewed from the promenade on the Amber road.',
      location: { lat: 26.9535, lng: 75.8462 },
      durationHours: 0.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Nahargarh Fort',
      type: 'sightseeing',
      description:
        'A ridge-top fort on the Aravallis with the best sunset view over the whole of Jaipur.',
      location: { lat: 26.9373, lng: 75.8155 },
      durationHours: 2,
      entryFee: 50,
      rating: 4.5,
      bestTime: 'evening',
    },
    {
      name: 'Galta Ji Temple',
      type: 'spiritual',
      description:
        'A pilgrimage site of temples and natural spring-fed tanks built into a narrow gorge east of the city.',
      location: { lat: 26.9165, lng: 75.8573 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Jhalana Leopard Safari',
      type: 'nature',
      description:
        'A jeep safari through a dry deciduous forest reserve inside the city limits with frequent leopard sightings.',
      location: { lat: 26.8551, lng: 75.8334 },
      durationHours: 3,
      entryFee: 1200,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Johari and Bapu Bazaar',
      type: 'shopping',
      description:
        'Old-city markets for gemstones, silver jewellery, block-printed textiles, mojari shoes and lac bangles.',
      location: { lat: 26.9196, lng: 75.8246 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'afternoon',
    },
    {
      name: 'Chokhi Dhani',
      type: 'food',
      description:
        'A recreated Rajasthani village with folk dance, puppet shows and a traditional thali dinner. The fee includes the meal.',
      location: { lat: 26.7665, lng: 75.8363 },
      durationHours: 3,
      entryFee: 900,
      rating: 4.3,
      bestTime: 'evening',
    },
  ],

  udaipur: [
    {
      name: 'City Palace Udaipur',
      type: 'culture',
      description:
        'A complex of eleven palaces built over 400 years on the bank of Lake Pichola, with mirror-work halls and peacock mosaics.',
      location: { lat: 24.5764, lng: 73.6835 },
      durationHours: 2.5,
      entryFee: 300,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Lake Pichola Boat Ride',
      type: 'sightseeing',
      description:
        'A boat trip from Rameshwar Ghat past the Lake Palace to Jag Mandir island, best in the golden hour before sunset.',
      location: { lat: 24.572, lng: 73.679 },
      durationHours: 1,
      entryFee: 500,
      rating: 4.6,
      bestTime: 'evening',
    },
    {
      name: 'Jagdish Temple',
      type: 'spiritual',
      description:
        'A 1651 Indo-Aryan temple to Vishnu reached by a steep flight of steps, covered in carved dancers and elephants.',
      location: { lat: 24.5797, lng: 73.6838 },
      durationHours: 0.5,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Bagore Ki Haveli',
      type: 'culture',
      description:
        'An 18th-century haveli museum at Gangaur Ghat that hosts the Dharohar folk dance and puppet show every evening.',
      location: { lat: 24.5799, lng: 73.6822 },
      durationHours: 1.5,
      entryFee: 150,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Saheliyon Ki Bari',
      type: 'nature',
      description:
        'The "Garden of the Maidens", laid out for the royal ladies with lotus pools, marble elephants and rain fountains.',
      location: { lat: 24.603, lng: 73.6862 },
      durationHours: 1,
      entryFee: 20,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Fateh Sagar Lake',
      type: 'nature',
      description:
        'A hill-ringed lake north of the old city with a lakeside drive, boat rides to Nehru Park and street-food stalls.',
      location: { lat: 24.6014, lng: 73.6742 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'afternoon',
    },
    {
      name: 'Sajjangarh Monsoon Palace',
      type: 'sightseeing',
      description:
        'A hilltop palace inside a wildlife sanctuary, built to watch the monsoon clouds, with wide sunset views of the lakes.',
      location: { lat: 24.5937, lng: 73.6397 },
      durationHours: 2,
      entryFee: 150,
      rating: 4.4,
      bestTime: 'evening',
    },
    {
      name: 'Karni Mata Ropeway',
      type: 'adventure',
      description:
        'A cable car from Deen Dayal Park up Machla Magra hill to the Karni Mata temple, with a bird’s-eye view of Pichola.',
      location: { lat: 24.5694, lng: 73.6858 },
      durationHours: 1,
      entryFee: 130,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Shilpgram',
      type: 'culture',
      description:
        'A rural arts and crafts village with traditional huts from western Indian states, working artisans and folk performers.',
      location: { lat: 24.6131, lng: 73.6634 },
      durationHours: 2,
      entryFee: 50,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Hathi Pol Bazaar',
      type: 'shopping',
      description:
        'The old-city market for miniature paintings, pichwai art, leather journals and tie-dye textiles.',
      location: { lat: 24.5868, lng: 73.6869 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.1,
      bestTime: 'afternoon',
    },
  ],

  munnar: [
    {
      name: 'Eravikulam National Park',
      type: 'nature',
      description:
        'Rolling shola grassland at Rajamalai, home to the endangered Nilgiri tahr. Park buses run from the entrance to the trail.',
      location: { lat: 10.1553, lng: 77.0617 },
      durationHours: 3,
      entryFee: 200,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Kolukkumalai Jeep Safari',
      type: 'adventure',
      description:
        'A rough jeep track from Suryanelli up to the world’s highest tea estate at 2,100 m, with views above the clouds at sunrise.',
      location: { lat: 10.0827, lng: 77.2218 },
      durationHours: 5,
      entryFee: 800,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Tea Museum Munnar',
      type: 'culture',
      description:
        'The KDHP museum at Nullatanni estate traces the history of tea in the High Range, with a working mini factory and tasting.',
      location: { lat: 10.0935, lng: 77.0509 },
      durationHours: 1.5,
      entryFee: 125,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Mattupetty Dam',
      type: 'sightseeing',
      description:
        'A reservoir among tea slopes and an Indo-Swiss dairy farm, with speed boats and the chance of wild elephants on the banks.',
      location: { lat: 10.1063, lng: 77.1237 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Echo Point',
      type: 'sightseeing',
      description:
        'A lakeside bend on the Top Station road where the hills throw your voice back across the water.',
      location: { lat: 10.1208, lng: 77.1517 },
      durationHours: 0.5,
      entryFee: 0,
      rating: 4.0,
      bestTime: 'any',
    },
    {
      name: 'Kundala Lake',
      type: 'nature',
      description:
        'A high-altitude arch-dam lake with pedal boats and shikaras, surrounded by cherry blossom in season.',
      location: { lat: 10.1436, lng: 77.1987 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Top Station',
      type: 'nature',
      description:
        'The highest point on the Munnar–Kodaikanal road at 1,700 m, looking down on the Tamil Nadu plains and the Theni valley.',
      location: { lat: 10.1236, lng: 77.2458 },
      durationHours: 1.5,
      entryFee: 25,
      rating: 4.4,
      bestTime: 'morning',
    },
    {
      name: 'Attukad Waterfalls',
      type: 'nature',
      description:
        'A waterfall in a narrow forested valley off the Pallivasal road, reached by a short walk through plantations.',
      location: { lat: 10.0535, lng: 77.0586 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Pothamedu View Point',
      type: 'nature',
      description:
        'A ridge a few kilometres from town with an open view over tea, coffee and cardamom estates, best near sunset.',
      location: { lat: 10.0615, lng: 77.0648 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'evening',
    },
    {
      name: 'Munnar Town Market',
      type: 'shopping',
      description:
        'Shops around the main bazaar selling estate-fresh tea, cardamom, pepper and homemade chocolate.',
      location: { lat: 10.0892, lng: 77.0597 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.0,
      bestTime: 'evening',
    },
  ],

  alleppey: [
    {
      name: 'Backwater Houseboat Cruise',
      type: 'sightseeing',
      description:
        'A day cruise on a converted rice barge from Punnamada jetty through the canals of Kuttanad, with a Kerala lunch on board.',
      location: { lat: 9.5087, lng: 76.354 },
      durationHours: 5,
      entryFee: 1500,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Backwater Kayaking at Kainakary',
      type: 'adventure',
      description:
        'A guided paddle through narrow village canals that houseboats cannot enter, starting soon after sunrise.',
      location: { lat: 9.479, lng: 76.387 },
      durationHours: 3,
      entryFee: 1000,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Alappuzha Beach',
      type: 'nature',
      description:
        'A long sandy beach with the remains of a 150-year-old sea pier, popular with locals at sunset.',
      location: { lat: 9.493, lng: 76.3176 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'evening',
    },
    {
      name: 'Alappuzha Lighthouse',
      type: 'sightseeing',
      description:
        'A red-and-white 1862 lighthouse near the beach; climb the spiral stairs for a view over the town and coast.',
      location: { lat: 9.4941, lng: 76.3204 },
      durationHours: 0.5,
      entryFee: 20,
      rating: 4.2,
      bestTime: 'afternoon',
    },
    {
      name: 'Marari Beach',
      type: 'nature',
      description:
        'A quiet fishing-village beach at Mararikulam, north of town, with clean sand and hammocks under the palms.',
      location: { lat: 9.601, lng: 76.2985 },
      durationHours: 3,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Pathiramanal Island',
      type: 'nature',
      description:
        'A small uninhabited island in Vembanad Lake reached by boat, known for migratory birds. The fee is a shared boat fare.',
      location: { lat: 9.6188, lng: 76.3847 },
      durationHours: 2.5,
      entryFee: 300,
      rating: 4.2,
      bestTime: 'morning',
    },
    {
      name: 'Ambalappuzha Sree Krishna Temple',
      type: 'spiritual',
      description:
        'A Kerala-style temple famous for its sweet milk payasam, offered daily for centuries.',
      location: { lat: 9.3836, lng: 76.3697 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Revi Karunakaran Museum',
      type: 'culture',
      description:
        'A private collection of Swarovski crystal, ivory, porcelain and Tanjore paintings gathered by a coir-exporting family.',
      location: { lat: 9.4992, lng: 76.3288 },
      durationHours: 1,
      entryFee: 150,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Krishnapuram Palace',
      type: 'culture',
      description:
        'An 18th-century Travancore palace near Kayamkulam housing Gajendra Moksham, one of the largest murals in Kerala.',
      location: { lat: 9.1497, lng: 76.5086 },
      durationHours: 1.5,
      entryFee: 35,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Mullakkal Street Market',
      type: 'shopping',
      description:
        'The town’s main bazaar around the Mullakkal Rajarajeswari temple, for coir products, banana chips and spices.',
      location: { lat: 9.4975, lng: 76.342 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.0,
      bestTime: 'any',
    },
  ],

  rishikesh: [
    {
      name: 'Ganga Rafting from Shivpuri',
      type: 'adventure',
      description:
        'A 16 km white-water run from Shivpuri to Rishikesh through grade III rapids such as Roller Coaster and Golf Course.',
      location: { lat: 30.1383, lng: 78.389 },
      durationHours: 3.5,
      entryFee: 1000,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Bungee Jumping at Mohan Chatti',
      type: 'adventure',
      description:
        'India’s highest fixed-platform bungee at 83 m, over a rocky tributary valley of the Ganga.',
      location: { lat: 30.0641, lng: 78.402 },
      durationHours: 3,
      entryFee: 4000,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Triveni Ghat Ganga Aarti',
      type: 'spiritual',
      description:
        'The main bathing ghat of the town, where priests perform the Maha Aarti with tiered lamps at dusk.',
      location: { lat: 30.1036, lng: 78.3049 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.7,
      bestTime: 'evening',
    },
    {
      name: 'Parmarth Niketan Ashram',
      type: 'spiritual',
      description:
        'The largest ashram in Rishikesh, on the east bank near Ram Jhula, with riverside gardens and daily yoga and satsang.',
      location: { lat: 30.1192, lng: 78.3122 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.7,
      bestTime: 'any',
    },
    {
      name: 'Ram Jhula',
      type: 'sightseeing',
      description:
        'A 230 m iron suspension footbridge across the Ganga linking Sivananda Ashram with the Swarg Ashram side.',
      location: { lat: 30.1236, lng: 78.3145 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Laxman Jhula',
      type: 'sightseeing',
      description:
        'The landmark 1929 suspension bridge at Tapovan, beside the thirteen-storey Trayambakeshwar temple.',
      location: { lat: 30.1263, lng: 78.3296 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Beatles Ashram',
      type: 'culture',
      description:
        'The abandoned ashram of Maharishi Mahesh Yogi where the Beatles stayed in 1968, now covered in murals inside Rajaji reserve.',
      location: { lat: 30.1136, lng: 78.3118 },
      durationHours: 1.5,
      entryFee: 150,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Neer Garh Waterfall',
      type: 'nature',
      description:
        'A short forest hike off the Badrinath road to a series of clear pools and cascades.',
      location: { lat: 30.1442, lng: 78.3373 },
      durationHours: 2,
      entryFee: 30,
      rating: 4.3,
      bestTime: 'morning',
    },
    {
      name: 'Kunjapuri Temple Viewpoint',
      type: 'nature',
      description:
        'A hilltop Shakti Peeth at 1,650 m with a panorama of the Swargarohini, Gangotri and Chaukhamba peaks, popular at sunrise.',
      location: { lat: 30.1836, lng: 78.3072 },
      durationHours: 3,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Tapovan Cafes',
      type: 'food',
      description:
        'Riverside cafes above Laxman Jhula serving vegetarian world food, wood-fired pizza and ginger-lemon-honey tea.',
      location: { lat: 30.13, lng: 78.325 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'afternoon',
    },
  ],

  varanasi: [
    {
      name: 'Ganga Boat Ride from Assi Ghat',
      type: 'sightseeing',
      description:
        'A rowing-boat trip downstream past the ghats, at its best at dawn after the Subah-e-Banaras morning aarti.',
      location: { lat: 25.2888, lng: 83.0062 },
      durationHours: 1.5,
      entryFee: 300,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Kashi Vishwanath Temple',
      type: 'spiritual',
      description:
        'The gold-spired temple of Shiva as Lord of the Universe, one of the twelve jyotirlingas, now reached by a wide corridor from the river.',
      location: { lat: 25.3109, lng: 83.0107 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Dashashwamedh Ghat Ganga Aarti',
      type: 'spiritual',
      description:
        'The nightly ceremony of fire, incense and conch shells performed by seven priests on the main ghat.',
      location: { lat: 25.3069, lng: 83.0104 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.8,
      bestTime: 'evening',
    },
    {
      name: 'Sarnath',
      type: 'culture',
      description:
        'The deer park where the Buddha gave his first sermon, with the Dhamek Stupa, monastery ruins and the Ashokan lion capital in the museum.',
      location: { lat: 25.3811, lng: 83.0245 },
      durationHours: 3,
      entryFee: 25,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Manikarnika Ghat Heritage Walk',
      type: 'culture',
      description:
        'A guided walk through the old-city lanes to the principal cremation ghat, explaining the rituals of Kashi.',
      location: { lat: 25.3108, lng: 83.0141 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Bharat Kala Bhavan, BHU',
      type: 'culture',
      description:
        'The university museum on the leafy BHU campus with miniature paintings, sculpture and Banarasi textiles.',
      location: { lat: 25.2714, lng: 82.9958 },
      durationHours: 2,
      entryFee: 20,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Ramnagar Fort',
      type: 'culture',
      description:
        'The 18th-century sandstone fort of the Maharaja of Banaras on the east bank, with a museum of vintage cars and palanquins.',
      location: { lat: 25.2694, lng: 83.0236 },
      durationHours: 1.5,
      entryFee: 75,
      rating: 4.0,
      bestTime: 'afternoon',
    },
    {
      name: 'Sankat Mochan Hanuman Temple',
      type: 'spiritual',
      description:
        'A much-loved Hanuman temple founded by the poet-saint Tulsidas, known for its besan laddoo prasad.',
      location: { lat: 25.2819, lng: 82.9994 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.7,
      bestTime: 'any',
    },
    {
      name: 'Kachori Gali Food Walk',
      type: 'food',
      description:
        'A tasting trail of kachori-sabzi, tamatar chaat, malaiyo and lassi in the lanes behind Vishwanath temple.',
      location: { lat: 25.3115, lng: 83.0123 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Thatheri Bazaar',
      type: 'shopping',
      description:
        'A lane of brassware and copperware workshops, close to the wholesale shops for Banarasi silk saris.',
      location: { lat: 25.312, lng: 83.011 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.2,
      bestTime: 'afternoon',
    },
  ],

  darjeeling: [
    {
      name: 'Tiger Hill',
      type: 'nature',
      description:
        'The 2,590 m viewpoint famous for first light on Kanchenjunga; on a clear day Everest is visible too. Leave by 4 am for sunrise.',
      location: { lat: 26.9949, lng: 88.2853 },
      durationHours: 2.5,
      entryFee: 50,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Batasia Loop',
      type: 'sightseeing',
      description:
        'A spiral of the toy-train track around a garden and the Gorkha war memorial, with Kanchenjunga as backdrop.',
      location: { lat: 27.0167, lng: 88.247 },
      durationHours: 1,
      entryFee: 20,
      rating: 4.3,
      bestTime: 'morning',
    },
    {
      name: 'Ghoom Monastery',
      type: 'spiritual',
      description:
        'The Yiga Choeling gompa of 1850, with a 4.5 m statue of the Maitreya Buddha and old Tibetan manuscripts.',
      location: { lat: 27.0115, lng: 88.251 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Toy Train Joy Ride',
      type: 'sightseeing',
      description:
        'A two-hour round trip on the UNESCO-listed Darjeeling Himalayan Railway to Ghum, India’s highest station.',
      location: { lat: 27.038, lng: 88.2627 },
      durationHours: 2,
      entryFee: 1500,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Himalayan Zoo and Mountaineering Institute',
      type: 'nature',
      description:
        'Padmaja Naidu zoo breeds red pandas and snow leopards; the same ticket covers the HMI museum founded after Tenzing’s Everest climb.',
      location: { lat: 27.0587, lng: 88.2545 },
      durationHours: 2.5,
      entryFee: 110,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Happy Valley Tea Estate',
      type: 'culture',
      description:
        'A working estate from 1854 just below town, with a guided factory tour on withering, rolling and grading, and a tasting.',
      location: { lat: 27.0511, lng: 88.2585 },
      durationHours: 1.5,
      entryFee: 100,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Darjeeling Ropeway',
      type: 'adventure',
      description:
        'A cable car from Singamari down over the tea gardens of the Rangeet valley and back.',
      location: { lat: 27.0613, lng: 88.2539 },
      durationHours: 1.5,
      entryFee: 200,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Japanese Peace Pagoda',
      type: 'spiritual',
      description:
        'A white Nipponzan Myohoji stupa with four gilded Buddha images, beside a small Japanese temple on Jalapahar hill.',
      location: { lat: 27.0276, lng: 88.259 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Glenary’s and Keventer’s',
      type: 'food',
      description:
        'Two colonial-era institutions on Nehru Road: a bakery-tearoom and a terrace cafe known for its English breakfast.',
      location: { lat: 27.0435, lng: 88.2665 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'afternoon',
    },
    {
      name: 'Chowrasta and Mall Road',
      type: 'shopping',
      description:
        'The traffic-free promenade at the top of the ridge, lined with tea shops, bookshops and curio stores.',
      location: { lat: 27.0453, lng: 88.2675 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'evening',
    },
  ],

  jaisalmer: [
    {
      name: 'Jaisalmer Fort',
      type: 'culture',
      description:
        'The 12th-century Sonar Quila, a living fort of yellow sandstone with the Raj Mahal palace museum inside its 99 bastions.',
      location: { lat: 26.9124, lng: 70.9126 },
      durationHours: 3,
      entryFee: 100,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Jain Temples of Jaisalmer Fort',
      type: 'spiritual',
      description:
        'Seven interconnected 15th-century temples inside the fort with finely carved sandstone. Open to visitors until noon.',
      location: { lat: 26.9118, lng: 70.911 },
      durationHours: 1,
      entryFee: 50,
      rating: 4.5,
      bestTime: 'morning',
    },
    {
      name: 'Patwon Ki Haveli',
      type: 'culture',
      description:
        'A cluster of five merchant mansions with sixty carved balconies, the most elaborate havelis in the city.',
      location: { lat: 26.9165, lng: 70.9149 },
      durationHours: 1,
      entryFee: 50,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Gadisar Lake',
      type: 'nature',
      description:
        'A 14th-century rainwater reservoir ringed by shrines and chhatris, with paddle boats and winter birdlife.',
      location: { lat: 26.909, lng: 70.922 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Bada Bagh',
      type: 'sightseeing',
      description:
        'Rows of royal cenotaphs on a low hill north of the city, beside an old dam and mango grove.',
      location: { lat: 26.954, lng: 70.887 },
      durationHours: 1,
      entryFee: 100,
      rating: 4.2,
      bestTime: 'any',
    },
    {
      name: 'Kuldhara Abandoned Village',
      type: 'culture',
      description:
        'The ruins of a Paliwal Brahmin village deserted overnight in the early 1800s, now a protected heritage site.',
      location: { lat: 26.8699, lng: 70.7851 },
      durationHours: 1.5,
      entryFee: 50,
      rating: 4.2,
      bestTime: 'afternoon',
    },
    {
      name: 'Sam Sand Dunes Camel Safari',
      type: 'adventure',
      description:
        'A camel ride onto the Thar dunes for sunset, followed by folk music and dinner at a desert camp.',
      location: { lat: 26.829, lng: 70.504 },
      durationHours: 4,
      entryFee: 800,
      rating: 4.6,
      bestTime: 'evening',
    },
    {
      name: 'Desert National Park',
      type: 'nature',
      description:
        'A jeep safari near Sudasari through scrub and dunes, one of the last habitats of the great Indian bustard.',
      location: { lat: 26.72, lng: 70.61 },
      durationHours: 3,
      entryFee: 600,
      rating: 4.2,
      bestTime: 'morning',
    },
    {
      name: 'Vyas Chhatri',
      type: 'sightseeing',
      description:
        'Sandstone cenotaphs on the edge of town dedicated to sage Vyasa, a favourite spot to watch the fort glow at sunset.',
      location: { lat: 26.923, lng: 70.903 },
      durationHours: 1,
      entryFee: 50,
      rating: 4.2,
      bestTime: 'evening',
    },
    {
      name: 'Sadar Bazaar Jaisalmer',
      type: 'shopping',
      description:
        'The main market below the fort for mirror-work textiles, camel-leather bags, silver and carved stone.',
      location: { lat: 26.915, lng: 70.915 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.1,
      bestTime: 'any',
    },
  ],

  kutch: [
    {
      name: 'White Rann at Dhordo',
      type: 'nature',
      description:
        'The endless salt flat of the Great Rann, walked at sunset or under a full moon. A permit is issued at Bhirandiyara check post.',
      location: { lat: 23.8304, lng: 69.5201 },
      durationHours: 3,
      entryFee: 100,
      rating: 4.7,
      bestTime: 'evening',
    },
    {
      name: 'Kalo Dungar',
      type: 'nature',
      description:
        'The Black Hill, highest point in Kutch at 462 m, with a Dattatreya temple and a panorama of the Rann.',
      location: { lat: 23.936, lng: 69.81 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.5,
      bestTime: 'afternoon',
    },
    {
      name: 'Aina Mahal and Prag Mahal',
      type: 'culture',
      description:
        'The 18th-century Hall of Mirrors and the neighbouring Italian-Gothic palace with a clock tower, in the old Darbargadh of Bhuj.',
      location: { lat: 23.254, lng: 69.668 },
      durationHours: 2,
      entryFee: 70,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Smritivan Earthquake Memorial',
      type: 'culture',
      description:
        'A memorial park and museum on Bhujiyo hill dedicated to the victims of the 2001 earthquake, with immersive galleries.',
      location: { lat: 23.2459, lng: 69.6945 },
      durationHours: 2.5,
      entryFee: 300,
      rating: 4.7,
      bestTime: 'any',
    },
    {
      name: 'Shree Swaminarayan Temple Bhuj',
      type: 'spiritual',
      description:
        'A marble temple rebuilt after the earthquake, with finely carved domes and pillars, close to Hamirsar Lake.',
      location: { lat: 23.2463, lng: 69.6646 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Bhujodi Weavers’ Village',
      type: 'shopping',
      description:
        'A Vankar weaving community east of Bhuj where you can watch handloom shawls being made and buy directly from the artisans.',
      location: { lat: 23.2248, lng: 69.7346 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Nirona Craft Village',
      type: 'culture',
      description:
        'Home of the last family practising Rogan painting, along with copper-bell makers and lacquer-work artisans.',
      location: { lat: 23.4651, lng: 69.5242 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Vijay Vilas Palace',
      type: 'culture',
      description:
        'A 1920s red-sandstone summer palace of the Kutch rulers at Mandvi, with a rooftop view to the sea.',
      location: { lat: 22.835, lng: 69.286 },
      durationHours: 1.5,
      entryFee: 50,
      rating: 4.4,
      bestTime: 'any',
    },
    {
      name: 'Mandvi Beach',
      type: 'nature',
      description:
        'A clean, windy beach lined with windmills, with camel rides and dabeli stalls. The wooden-ship yard is nearby on the Rukmavati.',
      location: { lat: 22.8256, lng: 69.3381 },
      durationHours: 2,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'evening',
    },
    {
      name: 'Dholavira',
      type: 'culture',
      description:
        'The excavated Harappan city on Khadir island with reservoirs, a citadel and a signboard in Indus script. A UNESCO World Heritage Site and a full-day trip from Bhuj.',
      location: { lat: 23.887, lng: 70.213 },
      durationHours: 6,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'any',
    },
  ],

  'leh-ladakh': [
    {
      name: 'Leh Palace',
      type: 'culture',
      description:
        'A nine-storey 17th-century royal palace modelled on the Potala, overlooking the old town and the Stok range.',
      location: { lat: 34.166, lng: 77.586 },
      durationHours: 1.5,
      entryFee: 25,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Shanti Stupa',
      type: 'spiritual',
      description:
        'A white-domed peace pagoda on Changspa hill, best at sunset when the whole Leh valley lights up.',
      location: { lat: 34.1738, lng: 77.5745 },
      durationHours: 1,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'evening',
    },
    {
      name: 'Leh Main Bazaar',
      type: 'shopping',
      description:
        'The pedestrianised market below the palace for pashmina, turquoise jewellery, prayer flags and dried apricots.',
      location: { lat: 34.164, lng: 77.585 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'evening',
    },
    {
      name: 'Hall of Fame',
      type: 'culture',
      description:
        'An Indian Army museum honouring soldiers of the Ladakh wars, with Siachen gear and a moving evening ceremony.',
      location: { lat: 34.139, lng: 77.556 },
      durationHours: 1.5,
      entryFee: 100,
      rating: 4.7,
      bestTime: 'any',
    },
    {
      name: 'Thiksey Monastery',
      type: 'spiritual',
      description:
        'A twelve-storey Gelugpa monastery stepping up a hillside, with a 15 m Maitreya Buddha and morning prayers open to visitors.',
      location: { lat: 34.0568, lng: 77.667 },
      durationHours: 2,
      entryFee: 50,
      rating: 4.7,
      bestTime: 'morning',
    },
    {
      name: 'Hemis Monastery',
      type: 'culture',
      description:
        'The largest and wealthiest monastery in Ladakh, hidden in a side gorge, with a museum of thangkas and ritual masks.',
      location: { lat: 33.9125, lng: 77.703 },
      durationHours: 2,
      entryFee: 100,
      rating: 4.6,
      bestTime: 'any',
    },
    {
      name: 'Magnetic Hill and Gurudwara Pathar Sahib',
      type: 'sightseeing',
      description:
        'A stretch of the Srinagar highway where an optical illusion makes vehicles appear to roll uphill, next to the army-run Pathar Sahib gurudwara.',
      location: { lat: 34.171, lng: 77.3525 },
      durationHours: 1.5,
      entryFee: 0,
      rating: 4.3,
      bestTime: 'any',
    },
    {
      name: 'Sangam Rafting at Nimmu',
      type: 'adventure',
      description:
        'Rafting on the Zanskar down to its confluence with the Indus at Nimmu, where the two rivers meet in different colours.',
      location: { lat: 34.165, lng: 77.333 },
      durationHours: 3,
      entryFee: 1800,
      rating: 4.5,
      bestTime: 'any',
    },
    {
      name: 'Khardung La',
      type: 'adventure',
      description:
        'A 5,359 m motorable pass on the road to Nubra, a rite of passage for bikers. Limit the stop at the top to 20 minutes.',
      location: { lat: 34.2787, lng: 77.6047 },
      durationHours: 4,
      entryFee: 0,
      rating: 4.6,
      bestTime: 'morning',
    },
    {
      name: 'Pangong Tso',
      type: 'nature',
      description:
        'A 134 km long lake at 4,350 m whose water shifts from turquoise to deep blue. A full-day excursion over Chang La; the fee covers the inner line permit.',
      location: { lat: 33.905, lng: 78.455 },
      durationHours: 6,
      entryFee: 400,
      rating: 4.8,
      bestTime: 'morning',
    },
  ],
};
