const cost = (stay, food, transport) => ({ stay, food, transport });

export const destinations = [
  {
    name: 'Manali',
    slug: 'manali',
    state: 'Himachal Pradesh',
    category: 'hill-station',
    tagline: 'Snow peaks, cedar forests and the road to Rohtang',
    description:
      'Manali sits at the head of the Kullu valley on the banks of the Beas, ringed by deodar forest and the Pir Panjal range. The old village, the wooden Hadimba temple and the hot springs at Vashisht are within walking distance, while Solang, the Atal Tunnel and Rohtang Pass make easy day trips for snow and adventure sports.',
    location: { lat: 32.2432, lng: 77.1892 },
    bestSeason: 'March – June, October – February for snow',
    idealDays: { min: 3, max: 5 },
    dailyCost: {
      economy: cost(1200, 500, 400),
      standard: cost(3000, 900, 900),
      luxury: cost(8500, 2000, 2200),
    },
    rating: 4.6,
    tags: ['mountains', 'snow', 'himalaya', 'honeymoon', 'trekking', 'paragliding'],
  },
  {
    name: 'Goa',
    slug: 'goa',
    state: 'Goa',
    category: 'beach',
    tagline: 'Sun-soaked beaches, Portuguese quarters and seafood shacks',
    description:
      'Goa pairs a hundred kilometres of Arabian Sea coastline with four and a half centuries of Portuguese heritage. The north is lively with beach shacks, markets and water sports; the south is quieter, with palm-lined coves such as Palolem. Inland lie the churches of Old Goa, spice plantations and the Dudhsagar falls.',
    location: { lat: 15.4909, lng: 73.8278 },
    bestSeason: 'November – February',
    idealDays: { min: 3, max: 6 },
    dailyCost: {
      economy: cost(1500, 600, 500),
      standard: cost(4000, 1200, 1000),
      luxury: cost(12000, 2800, 2500),
    },
    rating: 4.5,
    tags: ['beach', 'nightlife', 'seafood', 'churches', 'water sports', 'friends'],
  },
  {
    name: 'Jaipur',
    slug: 'jaipur',
    state: 'Rajasthan',
    category: 'heritage',
    tagline: 'The Pink City of hilltop forts, palaces and bazaars',
    description:
      'Founded in 1727 as one of India’s first planned cities, Jaipur is the gateway to Rajasthan. Amber Fort and Nahargarh watch over a walled old town of pink facades, where the City Palace, Hawa Mahal and the Jantar Mantar observatory stand a few minutes apart. The bazaars are known for gemstones, block prints and blue pottery.',
    location: { lat: 26.9124, lng: 75.7873 },
    bestSeason: 'October – March',
    idealDays: { min: 2, max: 4 },
    dailyCost: {
      economy: cost(1000, 450, 350),
      standard: cost(3000, 900, 800),
      luxury: cost(10000, 2200, 2000),
    },
    rating: 4.5,
    tags: ['forts', 'palaces', 'rajasthan', 'golden triangle', 'shopping', 'history'],
  },
  {
    name: 'Udaipur',
    slug: 'udaipur',
    state: 'Rajasthan',
    category: 'heritage',
    tagline: 'Lake palaces and sunsets over the Aravallis',
    description:
      'Udaipur, the former capital of Mewar, is built around a chain of man-made lakes in the Aravalli hills. The City Palace rises straight from the edge of Lake Pichola, facing the island Lake Palace, and the old town around Jagdish Temple is a maze of havelis, rooftop cafes and miniature-painting studios.',
    location: { lat: 24.5854, lng: 73.7125 },
    bestSeason: 'September – March',
    idealDays: { min: 2, max: 4 },
    dailyCost: {
      economy: cost(1200, 450, 350),
      standard: cost(3500, 1000, 800),
      luxury: cost(14000, 2500, 2200),
    },
    rating: 4.6,
    tags: ['lakes', 'palaces', 'rajasthan', 'romantic', 'mewar', 'history'],
  },
  {
    name: 'Munnar',
    slug: 'munnar',
    state: 'Kerala',
    category: 'hill-station',
    tagline: 'Rolling tea estates in the misty Western Ghats',
    description:
      'Munnar lies at about 1,600 metres in the Western Ghats, where three mountain streams meet among some of the highest tea estates in the world. Eravikulam National Park shelters the endangered Nilgiri tahr below Anamudi, South India’s highest peak, and the roads to Top Station and Kolukkumalai give wide views over the plantations.',
    location: { lat: 10.0889, lng: 77.0595 },
    bestSeason: 'September – March',
    idealDays: { min: 2, max: 4 },
    dailyCost: {
      economy: cost(1200, 400, 500),
      standard: cost(3200, 800, 1000),
      luxury: cost(9000, 1800, 2200),
    },
    rating: 4.5,
    tags: ['tea gardens', 'kerala', 'western ghats', 'honeymoon', 'wildlife', 'mist'],
  },
  {
    name: 'Alleppey',
    slug: 'alleppey',
    state: 'Kerala',
    category: 'nature',
    tagline: 'Houseboats drifting through Kerala’s backwaters',
    description:
      'Alleppey (Alappuzha) is the hub of the Kerala backwaters, a network of canals, lagoons and paddy fields lying below sea level in Kuttanad. Converted rice barges cruise from Punnamada Lake past villages, toddy shops and duck farms, while the town itself has a long beach, an old sea pier and a coir-trading past.',
    location: { lat: 9.4981, lng: 76.3388 },
    bestSeason: 'October – February',
    idealDays: { min: 2, max: 3 },
    dailyCost: {
      economy: cost(1300, 450, 400),
      standard: cost(3500, 900, 800),
      luxury: cost(11000, 2000, 2000),
    },
    rating: 4.4,
    tags: ['backwaters', 'houseboat', 'kerala', 'kuttanad', 'relaxing', 'beach'],
  },
  {
    name: 'Rishikesh',
    slug: 'rishikesh',
    state: 'Uttarakhand',
    category: 'adventure',
    tagline: 'White-water rafting and evening aarti on the Ganga',
    description:
      'Rishikesh is where the Ganga leaves the Himalayan foothills, and it is known equally for ashrams and for adventure. Mornings are for rafting the rapids below Shivpuri or bungee jumping at Mohan Chatti; evenings are for the Ganga aarti at Triveni Ghat and Parmarth Niketan. The town is vegetarian and alcohol-free.',
    location: { lat: 30.0869, lng: 78.2676 },
    bestSeason: 'September – November, February – May',
    idealDays: { min: 2, max: 4 },
    dailyCost: {
      economy: cost(800, 400, 300),
      standard: cost(2500, 800, 700),
      luxury: cost(9000, 1800, 1800),
    },
    rating: 4.5,
    tags: ['rafting', 'yoga', 'ganga', 'bungee', 'ashram', 'camping'],
  },
  {
    name: 'Varanasi',
    slug: 'varanasi',
    state: 'Uttar Pradesh',
    category: 'spiritual',
    tagline: 'Ghats, temple bells and dawn on the Ganga',
    description:
      'Varanasi, also called Kashi or Banaras, is one of the oldest continuously inhabited cities in the world and the holiest in Hinduism. More than eighty ghats line the western bank of the Ganga, best seen by boat at sunrise and during the evening aarti at Dashashwamedh. Sarnath, where the Buddha gave his first sermon, is a short drive away.',
    location: { lat: 25.3176, lng: 82.9739 },
    bestSeason: 'October – March',
    idealDays: { min: 2, max: 3 },
    dailyCost: {
      economy: cost(900, 350, 300),
      standard: cost(2800, 750, 650),
      luxury: cost(9500, 1800, 1700),
    },
    rating: 4.5,
    tags: ['ghats', 'kashi', 'banaras', 'ganga aarti', 'temples', 'street food'],
  },
  {
    name: 'Darjeeling',
    slug: 'darjeeling',
    state: 'West Bengal',
    category: 'hill-station',
    tagline: 'Toy train, tea gardens and Kanchenjunga at sunrise',
    description:
      'Darjeeling spreads along a ridge at 2,000 metres facing Kanchenjunga, the third-highest mountain in the world. The UNESCO-listed Darjeeling Himalayan Railway still runs steam joy rides to Ghum, the surrounding slopes produce the tea that carries the town’s name, and the sunrise from Tiger Hill is the classic early-morning outing.',
    location: { lat: 27.041, lng: 88.2663 },
    bestSeason: 'March – May, October – December',
    idealDays: { min: 2, max: 4 },
    dailyCost: {
      economy: cost(1200, 450, 450),
      standard: cost(3000, 850, 900),
      luxury: cost(9000, 1900, 2200),
    },
    rating: 4.4,
    tags: ['tea', 'toy train', 'kanchenjunga', 'himalaya', 'monasteries', 'sunrise'],
  },
  {
    name: 'Jaisalmer',
    slug: 'jaisalmer',
    state: 'Rajasthan',
    category: 'desert',
    tagline: 'A golden sandstone fort rising out of the Thar',
    description:
      'Jaisalmer grew rich on the camel-caravan trade, and its merchants left behind a living fort and havelis carved from honey-coloured sandstone. Around a quarter of the old town still lives inside the fort walls. West of the city the Thar desert begins, with camel safaris and overnight camps on the dunes at Sam.',
    location: { lat: 26.9157, lng: 70.9083 },
    bestSeason: 'November – February',
    idealDays: { min: 2, max: 3 },
    dailyCost: {
      economy: cost(1000, 450, 450),
      standard: cost(3000, 900, 1000),
      luxury: cost(12000, 2200, 2500),
    },
    rating: 4.4,
    tags: ['thar desert', 'camel safari', 'fort', 'rajasthan', 'dunes', 'havelis'],
  },
  {
    name: 'Kutch',
    slug: 'kutch',
    state: 'Gujarat',
    category: 'desert',
    tagline: 'The white salt desert and the craft villages of Gujarat',
    description:
      'Kutch is India’s largest district, stretching from the old walled town of Bhuj to the Great Rann, a seasonal salt marsh that dries into a white desert each winter. The villages around Bhuj are known for embroidery, weaving and Rogan painting, the coast at Mandvi has a shipbuilding yard and a palace, and the Harappan city of Dholavira is a UNESCO World Heritage Site.',
    location: { lat: 23.242, lng: 69.6669 },
    bestSeason: 'November – February (Rann Utsav)',
    idealDays: { min: 3, max: 5 },
    dailyCost: {
      economy: cost(1100, 400, 600),
      standard: cost(3000, 800, 1300),
      luxury: cost(9500, 1700, 2800),
    },
    rating: 4.4,
    tags: ['white rann', 'rann utsav', 'bhuj', 'gujarat', 'handicrafts', 'dholavira'],
  },
  {
    name: 'Leh-Ladakh',
    slug: 'leh-ladakh',
    state: 'Ladakh',
    category: 'adventure',
    tagline: 'High passes, blue lakes and cliff-top monasteries',
    description:
      'Leh, at 3,500 metres in the upper Indus valley, is the base for exploring Ladakh. Whitewashed monasteries such as Thiksey and Hemis sit on crags above the river, the road north climbs over Khardung La, and Pangong Tso lies a long day’s drive to the east. Keep the first day free to acclimatise to the altitude.',
    location: { lat: 34.1526, lng: 77.5771 },
    bestSeason: 'May – September',
    idealDays: { min: 5, max: 8 },
    dailyCost: {
      economy: cost(1400, 550, 900),
      standard: cost(3500, 1000, 1800),
      luxury: cost(11000, 2200, 3500),
    },
    rating: 4.7,
    tags: ['ladakh', 'pangong', 'road trip', 'monasteries', 'himalaya', 'bike trip'],
  },
].map((destination) => ({
  ...destination,
  country: 'India',
  heroImage: `/images/destinations/${destination.slug}.jpg`,
}));
